title: WPMU DEV Shared UI
baseurl: "/shared-ui" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
suiver: '2.12.2'
suiclass: 'sui-2-12-2'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# WordPress Admin Menu
adminmenu:
  - name: Setup
    url: /setup/
    icon: admin-tools
    children:
      - name: Installation
        url: /installation/
      - name: Requirements
        url: /requirements/
      - name: Whitelabel
        url: /whitelabel/
  - name: Basics
    url: /basics/
    icon: media-default
    children:
      - name: Heading
        url: /heading/
      - name: Typography
        url: /typography/
      - name: Colours
        url: /colours/
      - name: Icons
        url: /icons/
      - name: Layout
        url: /layout/
      - name: Footer
        url: /footer/
      - name: Utilities
        url: /utilities/
  - name: Containers
    url: /box-basics/
    icon: editor-table
    children:
      - name: Basic Box
        url: /box-basics/
      - name: Settings Box
        url: /box-settings/
      - name: Status Box
        url: /box-status/
      - name: Search Box
        url: /box-search/
      - name: Message Box
        url: /box-message/
  - name: Form Elements
    url: /form-field/
    icon: feedback
    children:
      - name: Form Field
        url: /form-field/
      - name: Labels
        url: /labels/
      - name: Inputs
        url: /inputs/
      - name: Password
        url: /password/
      - name: Textarea
        url: /textarea/
      - name: Radios
        url: /radios/
      - name: Checkbox
        url: /checkbox/
      - name: Toggles
        url: /toggles/
      - name: Select
        url: /select/
      - name: File Uploads
        url: /file-uploads/
      - name: Image Uploads
        url: /image-uploads/
      - name: Insert Variables
        url: /insert-variables/
      - name: Calendar
        url: /calendar/
      - name: Buttons
        url: /buttons/
      - name: Icon Buttons
        url: /icon-buttons/
      - name: WP Editor
        url: /wp-editor/
      - name: Multiple Strings
        url: /multistrings/
  - name: Simple Elements
    url: /notifications/
    icon: format-image
    children:
      - name: Notifications
        url: /notifications/
      - name: Tags
        url: /tags/
      - name: Tooltips
        url: /tooltips/
      - name: Status Dot
        url: /status-dot/
      - name: Tables
        url: /tables/
      - name: Scores
        url: /scores/
      - name: Progress Bar
        url: /progress-bar/
      - name: Code Snippets
        url: /code-snippets/
      - name: Code Editor
        url: /code-editor/
      - name: Dropdowns
        url: /dropdowns/
      - name: Field List
        url: /field-list/
      - name: Tree Selectors
        url: /trees/
      - name: Pagination
        url: /pagination/
      - name: Recipient
        url: /recipient/
  - name: Composite Elements
    url: /tabs/
    icon: format-gallery
    children:
      - name: Tabs
        url: /tabs/
      - name: Selectors
        url: /selectors/
      - name: Builder
        url: /builder/
      - name: Accordions
        url: /accordions/
      - name: Side Navigation
        url: /sidenav/
      - name: Modals
        url: /modals/
      - name: Summary
        url: /summary/
  - name: Upsells
    url: /upsells/
    icon: megaphone
    children:
      - name: Widget
        url: /upsell-widget/
      - name: Notice
        url: /upsell-notice/
      - name: Settings Box
        url: /upsell-box/
      - name: Upgrade Page
        url: /upgrade/

# SUI Base Colours
colours:
  - name: Monos
    children:
      - name: cloud
        hex: '#FAFAFA'
      - name: haze
        hex: '#F8F8F8'
      - name: smoke
        hex: '#F2F2F2'
      - name: silver
        hex: '#E6E6E6'
      - name: overcast
        hex: '#DDDDDD'
      - name: fiftyshades
        hex: '#AAAAAA'
      - name: grey
        hex: '#888888'
      - name: ironmike
        hex: '#666666'
      - name: nightrider
        hex: '#333333'
  - name: Primaries
    children:
      - name: blue
        hex: '#17A8E3'
      - name: green
        hex: '#1ABC9C'
      - name: yellow
        hex: '#FECF2F'
      - name: red
        hex: '#FF6D6D'
      - name: purple
        hex: '#8D00B1'
  - name: Ghosts
    children:
      - name: blue-ghost
        hex: '#E1F6FF'
      - name: green-ghost
        hex: '#D1F1EA'
      - name: yellow-ghost
        hex: '#FFF5D5'
      - name: red-ghost
        hex: '#FFE5E9'
      - name: purple-ghost
        hex: '#F9E1FF'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
